### PR TITLE
Proxy HTTP requests using 'binary' encoding

### PR DESCRIPTION
**Pull request by connorworley**
This seems to pass tests and meet my use case ¯\\\_(ツ)\_/¯

### CODE REVIEW

**Comment by connorworley** [comment]
This addresses the mangling described in #415. If it could be cut into a new version that would be excellent.

**Comment by bbyars** [comment]
Thanks! Does this close off issue #415?

Not fully released yet, but you can use the npm package mountebank-dev@2.1.0-beta.2844, which was based off this build.

**Comment by connorworley** [comment]
Indeed it does. Thanks for merging!

**Comment by bbyars** [comment]
Having to revert as it broke predicate matching for unicode (cirillic) characters (see #477). Adding a test to capture and will have to rethink the solution

**Pull request merged**
