### PR TITLE
 Switch from mailparser2 to mailparser npm package

### PR DESCRIPTION
**Pull request by sbwsg**
Fixes issue https://github.com/bbyars/mountebank/issues/409

The `mailparser2` package is a fork of `mailparser` but distributed under a more restrictive license. mailparser2 is provided under EUPLv1.1 only whereas mailparser is dual-licensed with both EUPLv1.1 and MIT.  This PR replaces `mailparser2` with `mailparser`.

I've separated this work into two commits. The first commit modifies `package.json` and `package-lock.json` to change the mailparser package and updates `smtpRequest.js` with the new mailparser require.  The second commit introduces the complete set of package modifications that come from running `npm install` against mountebank.  I split the commits in this way because my first attempt was to simply run `npm install mailparser@2.7.0` against master but that generated a massive diff of changes which I think would have been very difficult to review as a single commit.  As it stands this PR is still difficult to review because of all the package updates but at least in the first commit you can see the original intention.  Open to suggestions here if you've got a preferred way to avoid all the extraneous package noise.

Running grunt test largely succeeds with the following caveats:

- I had to run in airplane mode locally
- Testing without `airplane` on a remote VM I get the following 5 errors:

```
    IP blocking                                                                                                                                                                                                                                                                                                                                                                                                                         
      1) should only allow local requests if --localOnly used                                                                                                                                                                                                                                                                                                                                                                           
      2) should only allow local requests to http imposter if --localOnly used                                                                                                                                                                                                                                                                                                                                                          
      3) should only allow local requests to tcp imposter if --localOnly used                                                                                                                                                                                                                                                                                                                                                           
      4) should allow non-local requests if --localOnly not used                                                                                                                                                                                                                                                                                                                                                                        
      5) should block IPs not on --ipWhitelist
```

I'm suspicious that this is a problem with either the networking config on the VM or a permissions issue that's preventing binding to certain addresses.  I'm not entirely sure how to resolve it. Here's example error output for the 1st failing test:

```
  1) security                                                                                                                                                                                                                                                                                                                                                                                                                           
       IP blocking                                                                                                                                                                                                                                                                                                                                                                                                                      
         should only allow local requests if --localOnly used:                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                        
      AssertionError [ERR_ASSERTION]: Allowed nonlocal connection: [                                                                                                                                                                                                                                                                                                                                                                    
  {                                                                                                                                                                                                                                                                                                                                                                                                                                     
    "ip": "10...",                                                                                                                                                                                                                                                                                                                                                                                                                
    "canConnect": false,                                                                                                                                                                                                                                                                                                                                                                                                                
    "error": {                                                                                                                                                                                                                                                                                                                                                                                                                          
      "code": "ECONNRESET"                                                                                                                                                                                                                                                                                                                                                                                                              
    }                                                                                                                                                                                                                                                                                                                                                                                                                                   
  },                                                                                                                                                                                                                                                                                                                                                                                                                                    
  {                                                                                                                                                                                                                                                                                                                                                                                                                                     
    "ip": "fe80::...",                                                                                                                                                                                                                                                                                                                                                                                                     
    "canConnect": false,                                                                                                                                                                                                                                                                                                                                                                                                                
    "error": {                                                                                                                                                                                                                                                                                                                                                                                                                          
      "errno": "EINVAL",                                                                                                                                                                                                                                                                                                                                                                                                                
      "code": "EINVAL",                                                                                                                                                                                                                                                                                                                                                                                                                 
      "syscall": "bind",                                                                                                                                                                                                                                                                                                                                                                                                                
      "address": "fe80::..."                                                                                                                                                                                                                                                                                                                                                                                               
    }                                                                                                                                                                                                                                                                                                                                                                                                                                   
  }                                                                                                                                                                                                                                                                                                                                                                                                                                     
]
      + expected - actual

      -false
      +true

    at mb.start.then.then.rejections (functionalTest/commandLine/securityTest.js:242:28)
    at _fulfilled (node_modules/q/q.js:854:54)
    at /home/sbws/mountebank/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (node_modules/q/q.js:816:13)
    at /home/sbws/mountebank/node_modules/q/q.js:624:44
    at runSingle (node_modules/q/q.js:137:13)
    at flush (node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:9)
```

(I've trimmed the IP addresses above in case there's any risk of them being sensitive but they're both private addresses / "link-local" I believe.  Not too sure on the terminology here.)  I'll keep reading into this but I'm interested if you have any thoughts here on how to resolve or debug.

### CODE REVIEW

**Comment by sbwsg** [comment]
I'm a bit confused about the circleci failure - it appears that the lint warned about jquery but otherwise tests all passed.

**Comment by bbyars** [comment]
This is definitely my fault. I have some checks in there that aren't working for PRs. I'll fix shortly, in the middle of a death in the family so forgive a slow response.

Thank you so much for the fix

**Comment by bbyars** [comment]
I changed the build to ignore the spurious PR failures. I'm not sure why the non-airplane tests failed, but I suspect you're right that it's a permissions issue. The test you called out in particular tries to bind to local "loopback" interfaces, those IPs aren't in any way sensitive (they're largely the same on all machines).

Thanks again for the fix.

**Comment by sbwsg** [comment]
awesome, thankyou :raised_hands:

**Pull request merged**
